# Generated by Django 4.2.7 on 2025-07-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='department/about/')),
                ('alt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='POPSOPEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='departmentabout',
            name='department',
        ),
        migrations.RemoveField(
            model_name='popso',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='about',
        ),
        migrations.RemoveField(
            model_name='department',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='numberdata',
            name='department',
        ),
        migrations.AddField(
            model_name='departmentcontact',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='base.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benefit',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cta',
            name='heading',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='alt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='heading',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='alt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='blank_content',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='heading',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='numberdata',
            name='symbol',
            field=models.CharField(blank=True, choices=[('+', '+'), ('%', '%'), ('', 'None')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numberdata',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='programoffered',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='DepartmentAbout',
        ),
        migrations.DeleteModel(
            name='POPSO',
        ),
        migrations.AddField(
            model_name='popsopeo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_pso_peo', to='base.department'),
        ),
        migrations.AddField(
            model_name='aboutdepartment',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='base.department'),
        ),
        migrations.AddField(
            model_name='numberdata',
            name='about_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='base.aboutdepartment'),
            preserve_default=False,
        ),
    ]
