# Generated by Django 4.2.7 on 2025-07-16 07:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_aboutdepartment_popsopeo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='blank_content',
        ),
        migrations.AddField(
            model_name='facility',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutdepartment',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_sections', to='base.department'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='mission',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='vision',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='numberdata',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='popsopeo',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='programoffered',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='department/banners/')),
                ('alt', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='base.department')),
            ],
        ),
    ]
