# Generated by Django 4.2.7 on 2025-07-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_facility_blank_content_facility_content_and_more'),
    ]

    operations = [
    ]
