# Generated by Django 4.2.7 on 2025-07-19 12:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_aboutthedepartmentmodel_course_subjectsmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='about_the_department',
            new_name='about_the_course',
        ),
        migrations.CreateModel(
            name='AboutTheCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_course/')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_sections', to='base.course')),
            ],
        ),
        migrations.AlterField(
            model_name='numberdataatd',
            name='about_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_data', to='base.aboutthecoursemodel'),
        ),
        migrations.DeleteModel(
            name='AboutTheDepartmentModel',
        ),
    ]
