# Generated by Django 4.1.9 on 2025-07-21 06:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_about_the_department_course_about_the_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alt', models.CharField(help_text='Alt text for image', max_length=255)),
                ('image', models.ImageField(upload_to='faculty/images/')),
                ('mail_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('link', models.URLField(blank=True, help_text='Personal website or profile link', null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='General content about faculty', null=True)),
                ('qualification', ckeditor.fields.RichTextField(help_text='Educational qualifications')),
                ('bio', ckeditor.fields.RichTextField(help_text='Biography')),
                ('publication', ckeditor.fields.RichTextField(blank=True, help_text='Publications and research papers', null=True)),
                ('awards', ckeditor.fields.RichTextField(blank=True, help_text='Awards and recognitions', null=True)),
                ('workshop', ckeditor.fields.RichTextField(blank=True, help_text='Workshops conducted/attended', null=True)),
                ('work_experience', ckeditor.fields.RichTextField(blank=True, help_text='Work experience details', null=True)),
                ('projects', ckeditor.fields.RichTextField(blank=True, help_text='Projects handled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='base.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='base.designation')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='FacultyBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faculty/banners/')),
                ('alt', models.CharField(help_text='Alt text for banner image', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='base.faculty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
