# Generated by Django 4.1.9 on 2025-07-22 10:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_studentachievement_collegeachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('year_with_degree', models.CharField(help_text='e.g., 2023 B.Tech', max_length=100)),
                ('image', models.ImageField(upload_to='career_success/students/')),
                ('alt', models.CharField(help_text='Alt text for student image', max_length=255)),
                ('description', models.TextField()),
                ('company_image', models.ImageField(upload_to='career_success/companies/')),
                ('batch', models.CharField(help_text='e.g., 2019-2023', max_length=20)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_successes', to='base.department')),
            ],
            options={
                'verbose_name': 'Career Success',
                'verbose_name_plural': 'Career Successes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_opening', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('teaching', 'Teaching'), ('non-teaching', 'Non-Teaching')], max_length=20)),
                ('opening_position', models.CharField(max_length=255)),
                ('eligibility', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('apply_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_openings', to='base.department')),
            ],
            options={
                'verbose_name': 'Career Opening',
                'verbose_name_plural': 'Career Openings',
                'ordering': ['-created_at'],
            },
        ),
    ]
