# Generated by Django 4.1.9 on 2025-07-22 10:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_careersuccess_careeropening'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_events/images/')),
                ('alt', models.CharField(help_text='Alt text for accessibility', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Checkbox to activate/deactivate image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(help_text='Page title with brand name', max_length=200)),
                ('url', models.URLField(help_text='Canonical URL')),
                ('description', models.CharField(help_text='Meta description under 160 characters', max_length=160)),
                ('locale', models.CharField(default='en', help_text='Language locale', max_length=10)),
                ('type', models.CharField(default='article', help_text='Page type', max_length=50)),
                ('sitename', models.CharField(help_text='Site/brand name', max_length=100)),
                ('image', models.URLField(blank=True, help_text='Open Graph image URL', null=True)),
                ('charset', models.CharField(default='UTF-8', max_length=20)),
                ('viewport', models.CharField(default='width=device-width, initial-scale=1.0', max_length=100)),
                ('robots', models.CharField(default='index, follow', max_length=50)),
                ('author', models.CharField(help_text='Author or brand name', max_length=100)),
                ('canonical_url', models.URLField(help_text='Canonical URL for SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Data',
                'verbose_name_plural': 'Meta Data',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='NewsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('link', models.URLField(blank=True, help_text='External link for the news/event', null=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('events', 'Events'), ('announcement', 'Announcement'), ('student_activity', 'Student Activity'), ('research', 'Research')], max_length=20)),
                ('content', ckeditor.fields.RichTextField(help_text='Main content using CKEditor')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this news/event')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_events', to='base.department')),
                ('images', models.ManyToManyField(blank=True, related_name='news_events', to='base.imagemodel')),
                ('metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_event', to='base.metadata')),
                ('tags', models.ManyToManyField(blank=True, related_name='news_events', to='base.tagmodel')),
            ],
            options={
                'verbose_name': 'News & Event',
                'verbose_name_plural': 'News & Events',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
