# Generated by Django 4.1.9 on 2025-07-22 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_imagemodel_metadata_tagmodel_newsevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='placements/images/')),
                ('alt', models.CharField(help_text='Alt text for accessibility', max_length=255)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placement Image',
                'verbose_name_plural': 'Placement Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_name', models.CharField(max_length=255)),
                ('placement_number', models.CharField(help_text='Number value for placement statistic', max_length=50)),
                ('suffix', models.CharField(blank=True, choices=[('+', '+'), ('%', '%'), ('', 'None')], help_text='Symbol suffix like +, % or none', max_length=5, null=True)),
                ('text', models.CharField(help_text='Description text for the placement statistic', max_length=500)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placement Name',
                'verbose_name_plural': 'Placement Names',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_name', models.CharField(max_length=255)),
                ('number', models.CharField(help_text='Number value for research statistic', max_length=50)),
                ('suffix', models.CharField(blank=True, choices=[('+', '+'), ('%', '%'), ('', 'None')], help_text='Symbol suffix like +, % or none', max_length=5, null=True)),
                ('text', models.CharField(help_text='Description text for the research statistic', max_length=500)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Name',
                'verbose_name_plural': 'Research Names',
                'ordering': ['-created_at'],
            },
        ),
    ]
