# Generated by Django 4.2.7 on 2025-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stat_description',
            field=models.TextField(blank=True, help_text='Description or context for the statistic', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='stat_name',
            field=models.CharField(blank=True, help_text="Name of the statistical data (e.g., 'Students Enrolled')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='stat_number',
            field=models.IntegerField(blank=True, help_text='Numeric value for the statistic', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='stat_suffix',
            field=models.CharField(blank=True, help_text="Suffix text (e.g., '+', '%', 'years')", max_length=50, null=True),
        ),
    ]
