# Generated by Django 4.2.7 on 2025-10-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_course_stat_description_course_stat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='stat_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stat_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stat_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stat_suffix',
        ),
        migrations.AddField(
            model_name='department',
            name='stat_description',
            field=models.TextField(blank=True, help_text='Description or context for the statistic', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='stat_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured for display in other sections'),
        ),
        migrations.AddField(
            model_name='department',
            name='stat_name',
            field=models.CharField(blank=True, help_text="Name of the statistical data (e.g., 'Students Enrolled')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='stat_number',
            field=models.IntegerField(blank=True, help_text='Numeric value for the statistic', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='stat_suffix',
            field=models.CharField(blank=True, help_text="Suffix text (e.g., '+', '%', 'years')", max_length=50, null=True),
        ),
    ]
