# Generated by Django 4.2.7 on 2025-10-10 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_course_stat_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='stat_description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='stat_featured',
        ),
        migrations.RemoveField(
            model_name='department',
            name='stat_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='stat_number',
        ),
        migrations.RemoveField(
            model_name='department',
            name='stat_suffix',
        ),
        migrations.CreateModel(
            name='DepartmentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the statistical data (e.g., 'Students Enrolled')", max_length=255)),
                ('number', models.IntegerField(help_text='Numeric value for the statistic')),
                ('suffix', models.CharField(blank=True, help_text="Suffix text (e.g., '+', '%', 'years')", max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Description or context for the statistic', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured for display in other sections')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying statistics')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='base.department')),
            ],
            options={
                'verbose_name': 'Department Statistic',
                'verbose_name_plural': 'Department Statistics',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
