# Generated by Django 4.2.7 on 2025-10-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_department_stat_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programoffered',
            name='image',
        ),
        migrations.AddField(
            model_name='department',
            name='programs_image',
            field=models.ImageField(blank=True, help_text='Default image for all programs in this department', null=True, upload_to='department/programs/'),
        ),
    ]
