# Generated by Django 4.2.7 on 2025-10-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_programoffered_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programoffered',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Program Offered', 'verbose_name_plural': 'Programs Offered'},
        ),
        migrations.AddField(
            model_name='programoffered',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for displaying programs (0 = first)'),
        ),
    ]
