# Generated by Django 4.2.7 on 2025-10-10 13:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_programoffered_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='facilities_overview',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Overview/description for all facilities in this department', null=True),
        ),
    ]
