# Generated by Django 4.2.7 on 2025-10-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_department_facilities_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Company logo/image', null=True, upload_to='companies/')),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the company', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='careersuccess',
            name='company_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='about_the_course',
        ),
        migrations.DeleteModel(
            name='CourseContact',
        ),
        migrations.AddField(
            model_name='careersuccess',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company where the student is placed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_successes', to='base.company'),
        ),
    ]
