# Generated by Django 4.2.7 on 2025-10-14 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_company_remove_careersuccess_company_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(blank=True, help_text='Author name', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for this page'),
        ),
        migrations.AddField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether this is featured content'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether the content is published'),
        ),
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.TextField(blank=True, help_text='SEO keywords (comma-separated)'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (no enforced limit)'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_title',
            field=models.TextField(blank=True, help_text='SEO title (no enforced limit)'),
        ),
        migrations.AddField(
            model_name='course',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='og_image',
            field=models.CharField(blank=True, help_text='Open Graph image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (max 95 characters)', max_length=95),
        ),
        migrations.AddField(
            model_name='course',
            name='og_type',
            field=models.CharField(default='article', help_text='Open Graph type', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Publication date'),
        ),
        migrations.AddField(
            model_name='course',
            name='schema_json',
            field=models.TextField(blank=True, help_text='JSON-LD structured data for SEO (auto-generated, can be edited)'),
        ),
        migrations.AddField(
            model_name='course',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', help_text='Twitter Card type', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter Card description (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='twitter_image',
            field=models.CharField(blank=True, help_text='Twitter Card image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter Card title (max 70 characters)', max_length=70),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='author',
            field=models.CharField(blank=True, help_text='Author name', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for this page'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether this is featured content'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether the content is published'),
        ),
        migrations.AddField(
            model_name='department',
            name='keywords',
            field=models.TextField(blank=True, help_text='SEO keywords (comma-separated)'),
        ),
        migrations.AddField(
            model_name='department',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (no enforced limit)'),
        ),
        migrations.AddField(
            model_name='department',
            name='meta_title',
            field=models.TextField(blank=True, help_text='SEO title (no enforced limit)'),
        ),
        migrations.AddField(
            model_name='department',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='og_image',
            field=models.CharField(blank=True, help_text='Open Graph image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='department',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (max 95 characters)', max_length=95),
        ),
        migrations.AddField(
            model_name='department',
            name='og_type',
            field=models.CharField(default='article', help_text='Open Graph type', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Publication date'),
        ),
        migrations.AddField(
            model_name='department',
            name='schema_json',
            field=models.TextField(blank=True, help_text='JSON-LD structured data for SEO (auto-generated, can be edited)'),
        ),
        migrations.AddField(
            model_name='department',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', help_text='Twitter Card type', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter Card description (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='twitter_image',
            field=models.CharField(blank=True, help_text='Twitter Card image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='department',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter Card title (max 70 characters)', max_length=70),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='author',
            field=models.CharField(blank=True, help_text='Author name', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for this page'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether this is featured content'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Whether the content is published'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='keywords',
            field=models.TextField(blank=True, help_text='SEO keywords (comma-separated)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (no enforced limit)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='meta_title',
            field=models.TextField(blank=True, help_text='SEO title (no enforced limit)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='og_image',
            field=models.CharField(blank=True, help_text='Open Graph image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='faculty',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (max 95 characters)', max_length=95),
        ),
        migrations.AddField(
            model_name='faculty',
            name='og_type',
            field=models.CharField(default='article', help_text='Open Graph type', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Publication date'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='schema_json',
            field=models.TextField(blank=True, help_text='JSON-LD structured data for SEO (auto-generated, can be edited)'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', help_text='Twitter Card type', max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter Card description (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_image',
            field=models.CharField(blank=True, help_text='Twitter Card image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter Card title (max 70 characters)', max_length=70),
        ),
        migrations.AddField(
            model_name='faculty',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='author',
            field=models.CharField(blank=True, help_text='Author name', max_length=100),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for this page'),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether this is featured content'),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='keywords',
            field=models.TextField(blank=True, help_text='SEO keywords (comma-separated)'),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (no enforced limit)'),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='meta_title',
            field=models.TextField(blank=True, help_text='SEO title (no enforced limit)'),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='og_image',
            field=models.CharField(blank=True, help_text='Open Graph image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (max 95 characters)', max_length=95),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='og_type',
            field=models.CharField(default='article', help_text='Open Graph type', max_length=50),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Publication date'),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='schema_json',
            field=models.TextField(blank=True, help_text='JSON-LD structured data for SEO (auto-generated, can be edited)'),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', help_text='Twitter Card type', max_length=20),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter Card description (max 200 characters)', max_length=200),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='twitter_image',
            field=models.CharField(blank=True, help_text='Twitter Card image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter Card title (max 70 characters)', max_length=70),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
