# Generated by Django 4.2.7 on 2025-10-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_course_author_course_canonical_url_course_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programoffered',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Associated course (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_offerings', to='base.course'),
        ),
    ]
