# Generated by Django 4.2.7 on 2025-10-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_programoffered_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programoffered',
            unique_together={('department', 'course')},
        ),
    ]
