# Generated by Django 4.2.7 on 2025-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_programoffered_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_the_course',
            field=models.TextField(blank=True, null=True),
        ),
    ]
