# Generated by Django 4.2.7 on 2025-10-15 14:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_careersuccess_image_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdepartment',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutdepartment',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutdepartment',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutdepartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department/about/'),
        ),
        migrations.AlterField(
            model_name='aboutthecoursemodel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutthecoursemodel',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department/banners/'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='department/benefits/'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benefitsmodel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='benefits_icons/'),
        ),
        migrations.AlterField(
            model_name='benefitsmodel',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='coursecontact',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontact',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontact',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontact',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cta',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cta',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctamodel',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ctamodel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='department/curriculum/'),
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department/contacts/'),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='departmentstatistics',
            name='name',
            field=models.CharField(blank=True, help_text="Name of the statistical data (e.g., 'Students Enrolled')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='departmentstatistics',
            name='number',
            field=models.IntegerField(blank=True, help_text='Numeric value for the statistic', null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department/facilities/'),
        ),
        migrations.AlterField(
            model_name='facultybanner',
            name='alt',
            field=models.CharField(blank=True, help_text='Alt text for banner image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facultybanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/banners/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='alt',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_events/images/'),
        ),
        migrations.AlterField(
            model_name='labmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labmodel',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='labs/'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='author',
            field=models.CharField(blank=True, help_text='Author or brand name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO', null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='description',
            field=models.CharField(blank=True, help_text='Meta description under 160 characters', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='page_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='sitename',
            field=models.CharField(blank=True, help_text='Site/brand name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(blank=True, help_text='Page title with brand name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='url',
            field=models.URLField(blank=True, help_text='Canonical URL', null=True),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='category',
            field=models.CharField(blank=True, choices=[('news', 'News'), ('events', 'Events'), ('announcement', 'Announcement'), ('student_activity', 'Student Activity'), ('research', 'Research')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Main content using CKEditor', null=True),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_events', to='base.department'),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='numberdata',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='numberdata',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='numberdata',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='numberdataatd',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numberdataatd',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='popsopeo',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programoffered',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programoffered',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programoffered',
            name='explore_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quicklinksmodel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quicklinksmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjectsmodel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
