# Generated by Django 4.2.7 on 2025-11-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_aboutdepartment_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='cta_type',
            field=models.CharField(blank=True, choices=[('about', 'About Department'), ('curriculum', 'Curriculum'), ('general', 'General')], default='general', help_text='Type of CTA to distinguish between different sections', max_length=20, null=True),
        ),
    ]
