# Generated by Django 4.2.7 on 2025-11-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_add_cta_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentstatistics',
            name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='programs_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for programs image', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='departmentstatistics',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the statistic', null=True, upload_to='department/statistics/'),
        ),
        migrations.AddField(
            model_name='departmentstatistics',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for statistic image', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='link',
            field=models.URLField(blank=True, help_text='Link for the facility (optional)', null=True),
        ),
        migrations.AddField(
            model_name='programoffered',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for this program', null=True, upload_to='department/programs/'),
        ),
        migrations.AddField(
            model_name='programoffered',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for program image', max_length=200, null=True),
        ),
    ]
