# Generated by Django 4.2.7 on 2025-11-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_v3_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.RemoveField(
            model_name='departmentstatistics',
            name='image',
        ),
        migrations.RemoveField(
            model_name='departmentstatistics',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='link',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='link_blank',
        ),
        migrations.RemoveField(
            model_name='programoffered',
            name='image',
        ),
        migrations.RemoveField(
            model_name='programoffered',
            name='image_alt',
        ),
        migrations.AlterField(
            model_name='facility',
            name='content',
            field=models.CharField(blank=True, help_text='Content for the facility', max_length=500, null=True),
        ),
    ]
