# Generated by Django 4.2.7 on 2025-11-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_v4_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='course',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='labmodel',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='labmodel',
            name='link_blank',
        ),
        migrations.AddField(
            model_name='ctamodel',
            name='cta_type',
            field=models.CharField(blank=True, choices=[('about', 'About the Course'), ('general', 'General')], default='general', help_text='Type of CTA to distinguish between different sections', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labmodel',
            name='content',
            field=models.CharField(blank=True, help_text='Content for the lab', max_length=500, null=True),
        ),
    ]
