# Generated by Django 4.2.7 on 2025-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_v5_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='page_url',
            field=models.URLField(blank=True, help_text='Page URL for this course', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='page_url',
            field=models.URLField(blank=True, help_text='Page URL for this department', null=True),
        ),
    ]
