# Generated by Django 4.2.7 on 2025-11-01 14:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_add_page_url_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculummodel',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='name',
        ),
        migrations.RemoveField(
            model_name='curriculummodel',
            name='link_file',
        ),
        migrations.RemoveField(
            model_name='curriculummodel',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if not provided)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image', null=True, upload_to='department/curriculum/'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link', null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='title',
            field=models.CharField(blank=True, help_text='Title for the curriculum entry', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curriculummodel',
            name='file',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='curriculum_files/'),
        ),
        migrations.AddField(
            model_name='curriculummodel',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image', null=True, upload_to='curriculum_files/'),
        ),
        migrations.AddField(
            model_name='curriculummodel',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link', null=True),
        ),
        migrations.AddField(
            model_name='curriculummodel',
            name='title',
            field=models.CharField(blank=True, help_text='Title for the curriculum entry', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if not provided)', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description/details for the curriculum', null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='file',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='department/curriculum/'),
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description/details for the curriculum', null=True),
        ),
    ]
