# Generated by Django 4.2.7 on 2025-11-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_v6_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='department',
            name='page_url',
        ),
    ]
