# Generated by Django 4.2.7 on 2025-11-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_page_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.TextField(blank=True, help_text='Description/details for the curriculum', null=True),
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='description',
            field=models.TextField(blank=True, help_text='Description/details for the curriculum', null=True),
        ),
    ]
