# Generated by Django 4.2.7 on 2025-11-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_layout_and_curriculum_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='image',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='link',
        ),
        migrations.RemoveField(
            model_name='curriculummodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='curriculummodel',
            name='link',
        ),
    ]
