# Generated by Django 4.2.7 on 2025-11-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_curriculum_image_link_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='content',
        ),
        migrations.RemoveField(
            model_name='labmodel',
            name='content',
        ),
        migrations.AlterField(
            model_name='quicklink',
            name='link',
            field=models.CharField(blank=True, help_text='Link URL (no validation restrictions)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quicklinksmodel',
            name='link',
            field=models.CharField(blank=True, help_text='Link URL (no validation restrictions)', max_length=500, null=True),
        ),
    ]
