# Generated by Django 4.2.7 on 2025-11-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_remove_content_field_and_update_quicklinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careersuccess',
            name='year_with_degree',
        ),
    ]
