# Generated by Django 4.2.7 on 2025-11-01 18:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_year_with_degree_from_career_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentachievement',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
