# Generated by Django 4.2.7 on 2025-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_make_student_achievement_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevents',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from heading if not provided)', max_length=255, null=True, unique=True),
        ),
    ]
