# Generated by Django 4.2.7 on 2025-11-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_add_slug_field_to_news_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='content',
        ),
        migrations.AddField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name if not provided)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(blank=True, help_text='Educational qualifications', max_length=500, null=True),
        ),
    ]
