# Generated by Django 4.2.7 on 2025-11-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_faculty_model_updates_remove_banner_content_add_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentachievement',
            name='alt',
            field=models.CharField(blank=True, help_text='Alt text for image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the achievement', null=True, upload_to='achievements/student/'),
        ),
    ]
