# Generated by Django 4.2.7 on 2025-11-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_make_student_achievement_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentachievement',
            name='achievement_name',
            field=models.CharField(blank=True, help_text='Name of the achievement', max_length=255, null=True),
        ),
    ]
