# Generated by Django 4.2.7 on 2025-11-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_add_achievement_name_to_student_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Canonical URL for this page (supports both absolute URLs and relative paths)', max_length=500),
        ),
        migrations.AlterField(
            model_name='department',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Canonical URL for this page (supports both absolute URLs and relative paths)', max_length=500),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Canonical URL for this page (supports both absolute URLs and relative paths)', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Canonical URL for this page (supports both absolute URLs and relative paths)', max_length=500),
        ),
    ]
