# Generated by Django 4.2.7 on 2025-11-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_change_canonical_url_to_charfield'),
    ]

    operations = [
    ]
