# Generated by Django 4.2.7 on 2025-11-02 10:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_move_popsopeo_from_department_to_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popsopeo',
            options={'ordering': ['name'], 'verbose_name': 'PO-PSO-PEO', 'verbose_name_plural': 'PO-PSO-PEO'},
        ),
        migrations.RemoveField(
            model_name='popsopeo',
            name='department',
        ),
        migrations.AddField(
            model_name='popsopeo',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_pso_peo', to='base.course'),
        ),
        migrations.AddField(
            model_name='popsopeo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popsopeo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='popsopeo',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for PO, PSO, or PEO', null=True),
        ),
        migrations.AlterField(
            model_name='popsopeo',
            name='name',
            field=models.CharField(blank=True, help_text='PO, PSO, or PEO', max_length=200, null=True),
        ),
    ]
