# Generated by Django 4.2.7 on 2025-11-02 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_popsopeo_options_remove_popsopeo_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lab_overview',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Overview/description for all labs in this course', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='misc',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Miscellaneous content for the course', null=True),
        ),
    ]
