# Generated by Django 4.2.7 on 2025-11-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_add_lab_overview_and_misc_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='og_locale',
            field=models.CharField(blank=True, default='en_US', help_text='Open Graph locale (e.g., en_US)', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='og_site_name',
            field=models.CharField(blank=True, help_text='Open Graph site name (e.g., SRM TRP Trichy)', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='og_url',
            field=models.CharField(blank=True, help_text='Open Graph URL (auto-generated if not provided)', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='robots',
            field=models.CharField(blank=True, default='follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large', help_text='Robots meta tag content', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='twitter_data1',
            field=models.CharField(blank=True, help_text='Twitter Card data 1 (e.g., author name)', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='twitter_data2',
            field=models.CharField(blank=True, default='Less than a minute', help_text='Twitter Card data 2 (e.g., reading time)', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='twitter_label1',
            field=models.CharField(blank=True, default='Written by', help_text='Twitter Card label 1', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='twitter_label2',
            field=models.CharField(blank=True, default='Time to read', help_text='Twitter Card label 2', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='og_locale',
            field=models.CharField(blank=True, default='en_US', help_text='Open Graph locale (e.g., en_US)', max_length=10),
        ),
        migrations.AddField(
            model_name='department',
            name='og_site_name',
            field=models.CharField(blank=True, help_text='Open Graph site name (e.g., SRM TRP Trichy)', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='og_url',
            field=models.CharField(blank=True, help_text='Open Graph URL (auto-generated if not provided)', max_length=500),
        ),
        migrations.AddField(
            model_name='department',
            name='robots',
            field=models.CharField(blank=True, default='follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large', help_text='Robots meta tag content', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='twitter_data1',
            field=models.CharField(blank=True, help_text='Twitter Card data 1 (e.g., author name)', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='twitter_data2',
            field=models.CharField(blank=True, default='Less than a minute', help_text='Twitter Card data 2 (e.g., reading time)', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='twitter_label1',
            field=models.CharField(blank=True, default='Written by', help_text='Twitter Card label 1', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='twitter_label2',
            field=models.CharField(blank=True, default='Time to read', help_text='Twitter Card label 2', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='og_locale',
            field=models.CharField(blank=True, default='en_US', help_text='Open Graph locale (e.g., en_US)', max_length=10),
        ),
        migrations.AddField(
            model_name='faculty',
            name='og_site_name',
            field=models.CharField(blank=True, help_text='Open Graph site name (e.g., SRM TRP Trichy)', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='og_url',
            field=models.CharField(blank=True, help_text='Open Graph URL (auto-generated if not provided)', max_length=500),
        ),
        migrations.AddField(
            model_name='faculty',
            name='robots',
            field=models.CharField(blank=True, default='follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large', help_text='Robots meta tag content', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_data1',
            field=models.CharField(blank=True, help_text='Twitter Card data 1 (e.g., author name)', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_data2',
            field=models.CharField(blank=True, default='Less than a minute', help_text='Twitter Card data 2 (e.g., reading time)', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_label1',
            field=models.CharField(blank=True, default='Written by', help_text='Twitter Card label 1', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_label2',
            field=models.CharField(blank=True, default='Time to read', help_text='Twitter Card label 2', max_length=50),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='og_locale',
            field=models.CharField(blank=True, default='en_US', help_text='Open Graph locale (e.g., en_US)', max_length=10),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='og_site_name',
            field=models.CharField(blank=True, help_text='Open Graph site name (e.g., SRM TRP Trichy)', max_length=100),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='og_url',
            field=models.CharField(blank=True, help_text='Open Graph URL (auto-generated if not provided)', max_length=500),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='robots',
            field=models.CharField(blank=True, default='follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large', help_text='Robots meta tag content', max_length=200),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='twitter_data1',
            field=models.CharField(blank=True, help_text='Twitter Card data 1 (e.g., author name)', max_length=100),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='twitter_data2',
            field=models.CharField(blank=True, default='Less than a minute', help_text='Twitter Card data 2 (e.g., reading time)', max_length=50),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='twitter_label1',
            field=models.CharField(blank=True, default='Written by', help_text='Twitter Card label 1', max_length=50),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='twitter_label2',
            field=models.CharField(blank=True, default='Time to read', help_text='Twitter Card label 2', max_length=50),
        ),
    ]
